### PR TITLE
Fix/incorrect timezone comparison

### PR DESCRIPTION
**Pull request by TomLingham**
This builds off the Pull Request that was created by @samxsmith [here](https://github.com/shichongrui/obsidian-rollover-daily-todos/pull/11).

### CODE REVIEW

**Comment by joelpittet** [comment]
This look like it may conflict with #11 if it gets in.

**Comment by TomLingham** [comment]
This shouldn't conflict 🙂 I used #11 as a base (unless it gets updated, I may need to rebase in that case).

The reason I based off #11 was because it also appears to address a portion of the issue.

**Comment by joelpittet** [comment]
Rebase just because they change the same file is what I meant :)

**Comment by TomLingham** [comment]
Awesome. It's already rebased and up to date 😄

**Comment by joelpittet** [comment]
@TomLingham maybe you can review the other PR code, it looks like it needs one more.

**Pull request merged**
